---
Name: serialised-db-fields
---
SilverStripe\Core\Injector\Injector:
  JSONField:
    class: UncleCheese\SerialisedDBFields\JSONField
    properties:
      parser: '%$UncleCheese\SerialisedDBFields\JSONParser'
  YAMLField:
    class: UncleCheese\SerialisedDBFields\YAMLField
    properties:
      parser: '%$UncleCheese\SerialisedDBFields\YAMLParser'
